/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marklogic.client.examples.app;

import marklogic.client.examples.list.LinkedList;

import static marklogic.client.examples.utilities.StringUtils.join;
import static marklogic.client.examples.utilities.StringUtils.split;
import static marklogic.client.examples.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
